// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPtQehtltLruHNtCaCI3qvpeoEc05yBiU',
    appId: '1:909346740133:web:dec8e7fd302600c22c7a4c',
    messagingSenderId: '909346740133',
    projectId: 'pentagram-smt5',
    authDomain: 'pentagram-smt5.firebaseapp.com',
    storageBucket: 'pentagram-smt5.firebasestorage.app',
    measurementId: 'G-QJGR9K6GZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvpiHMe2o82fFRG5Q0imPOCzK1riz5GDo',
    appId: '1:909346740133:android:dd8262e93df31a382c7a4c',
    messagingSenderId: '909346740133',
    projectId: 'pentagram-smt5',
    storageBucket: 'pentagram-smt5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTvY8LMZgH51USRaJ7LkM1aTdKIFxOajo',
    appId: '1:909346740133:ios:36c5c4a9a59c88082c7a4c',
    messagingSenderId: '909346740133',
    projectId: 'pentagram-smt5',
    storageBucket: 'pentagram-smt5.firebasestorage.app',
    iosBundleId: 'com.example.pentagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTvY8LMZgH51USRaJ7LkM1aTdKIFxOajo',
    appId: '1:909346740133:ios:36c5c4a9a59c88082c7a4c',
    messagingSenderId: '909346740133',
    projectId: 'pentagram-smt5',
    storageBucket: 'pentagram-smt5.firebasestorage.app',
    iosBundleId: 'com.example.pentagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPtQehtltLruHNtCaCI3qvpeoEc05yBiU',
    appId: '1:909346740133:web:557512721af327992c7a4c',
    messagingSenderId: '909346740133',
    projectId: 'pentagram-smt5',
    authDomain: 'pentagram-smt5.firebaseapp.com',
    storageBucket: 'pentagram-smt5.firebasestorage.app',
    measurementId: 'G-DENMKYQ9JE',
  );
}
