# GitHub Actions workflow to deploy Flutter Web to Firebase Hosting on PR
name: Deploy Flutter Web to Firebase Hosting on PR

on:
  workflow_dispatch:
  pull_request:
#    branches-ignore:
#      - prod

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: flutter build web

      - name: Deploy to Firebase Hosting (Preview)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PENTAGRAM_SMT5 }}
          projectId: pentagram-smt5
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks