# GitHub Actions workflow to deploy Flutter Web to Firebase Hosting on prod branch
name: Deploy Flutter Web to Firebase Hosting on merge to prod

on:
  push:
    branches:
      - prod

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: flutter build web

      - name: Deploy to Firebase Hosting (Production)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LLM_FOR_AUTISM }}
          projectId: llm-for-autism
          channelId: live
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks